site_name: HPC Slurm (Rev.0)
nav:
        - Overview: index.md
        - Getting Started: get_started.md
        - SBatch: sbatch.md
        - Commands: commands.md
        - FAQ: faq.md
theme: readthedocs
extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
